apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://otel-demo-kv-dev12333.vault.azure.net"

      serviceAccountRef:
        name: eso-keyvault
        namespace: external-secrets