apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-keyvault
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "18a234f2-b473-4f15-b374-43f7cfeb8e6f"
    azure.workload.identity/tenant-id: "69ad6afc-a613-4f66-87c3-454b7ee96519"